let Allpictures = [
    {
        id:1,
        image:'../imges/flower1.jpg',
        category:'flower',
        desc:'Yellow Flower'
    },
    {
        id:2,
        image:'../imges/flower2.jpg',
        category:'flower',
        desc:'Yellow Sun-Flower'
    },
    {
        id:3,
        image:'../imges/flower3.jpg',
        category:'flower',
        desc:'Light Pink-Flower'
    },
    {
        id:4,
        image:'../imges/Flower4.jpg',
        category:'flower',
        desc:'Pink-Flower'
    },
    {
        id:5,
        image:'../imges/home.jpg',
        category:'home',
        desc:'Home Hall Design'
    },
    {
        id:6,
        image:'../imges/homeinner.png',
        category:'home',
        desc:'Room Side Design'
    },
    {
        id:7,
        image:'../imges/homeinner2.png',
        category:'home',
        desc:'Hall Design'
    },
    {
        id:8,
        image:'../imges/homeinner3.png',
        category:'home',
        desc:'Main Hall Design'
    },
    {
        id:10,
        image:'../imges/homeinner5.jpg',
        category:'home',
        desc:'Main Hall Design'
    },
    {
        id:9,
        image:'../imges/homeinner4.png',
        category:'home',
        desc:'Main Hall Design............'
    },
    {
        id:11,
        image:'../imges/homeinner6.png',
        category:'home',
        desc:'Inside Door Decoration'
    },
    {
        id:12,
        image:'../imges/mon1.jpg',
        category:'mountain',
        desc:'Mountains'
    },
    {
        id:13,
        image:'../imges/mount.jpg',
        category:'mountain',
        desc:'Mountains'
    },
    {
        id:14,
        image:'../imges/mount2.jpg',
        category:'mountain',
        desc:'Mountains'
    },
    {
        id:15,
        image:'../imges/mount3.jpg',
        category:'mountain',
        desc:'Mountains'
    },
    {
        id:16,
        image:'../imges/mount4.jpg',
        category:'mountain',
        desc:'Mountains'
    },
    {
        id:17,
        image:'../imges/mount5.jpg',
        category:'mountain',
        desc:'Mountains'
    },
    {
        id:18,
        image:'../imges/mount6.jpg',
        category:'mountain',
        desc:'Mountains'
    },
    {
        id:19,
        image:'../imges/mount7.jpg',
        category:'mountain',
        desc:'Mountains'
    },
    {
        id:20,
        image:'../imges/see1.jpg',
        category:'sea',
        desc:'SEA'
    },
    {
        id:21,
        image:'../imges/see2.jpg',
        category:'sea',
        desc:'SEA'
    },
    {
        id:22,
        image:'../imges/see 3.jpg',
        category:'sea',
        desc:'SEA'
    },
    {
        id:23,
        image:'../imges/see4.jpg',
        category:'sea',
        desc:'SEA'
    },
    {
        id:24,
        image:'../imges/see5.jpg',
        category:'sea',
        desc:'SEA'
    },
    {
        id:25,
        image:'../imges/see6.jpg',
        category:'sea',
        desc:'SEA'
    },
    {
        id:26,
        image:'../imges/road.jpg',
        category:'road',
        desc:'Road'
    },
    {
        id:27,
        image:'../imges/home7.jpg',
        category:'home',
        desc:'Room Design'
    },
    {
        id:28,
        image:'../imges/home8.jpg',
        category:'home',
        desc:'Hall'
    },
]
export default Allpictures;